import fs from 'fs';
import path from 'path';
import url from 'url';

import { AUTO_GENERATED_NOTE } from './autoGeneratedNote.js';
import { convertRuleOptionsToTypescriptTypes } from './convertRuleOptionsToTypes.js';
import { formatText, toPascalCase } from './format.js';
import { getAllPlugins, type Plugin } from './getPlugins.js';

const __dirname = url.fileURLToPath(new URL('.', import.meta.url));

export async function generateTypes(): Promise<void> {
  const plugins = getAllPlugins();

  for await (const plugin of plugins) {
    if (!plugin.rules) {
      continue;
    }

    const rules: Plugin['rules'] = {};
    for (const [ruleName, rule] of Object.entries(plugin.rules)) {
      if (typeof rule === 'function') {
        // normalise functional rules
        rules[ruleName] = {
          defaultOptions: [],
          meta: {
            messages: {},
            schema: {},
            type: 'suggestion',
          },
          create: rule,
        };
      } else if (rule.meta.deprecated === true) {
        // filter deprecated rules
        continue;
      } else {
        rules[ruleName] = rule;
      }
    }

    await convertRuleOptionsToTypescriptTypes({
      ...plugin,
      rules,
    });

    const ruleNames = Object.keys(rules).map((rule) => ({
      name: rule,
      safeName: toPascalCase(rule.replace(`${plugin.shortName}/`, '')),
    }));
    const interfaceName = toPascalCase(plugin.shortName);

    const rulePrefix =
      plugin.shortName === 'eslint' ? '' : `${plugin.shortName}/`;

    const typesFile = [
      AUTO_GENERATED_NOTE,
      '',
      ...ruleNames.map(
        (rule) =>
          `import type { ${rule.safeName} } from '../${plugin.shortName}/${rule.name}.js'`
      ),
      '',
      `interface ${interfaceName} {`,
      ...ruleNames.map(
        (rule) => `'${rulePrefix}${rule.name}': ${rule.safeName};`
      ),
      '}',
      '',
      'export type {',
      `    ${interfaceName}`,
      '};',
      '',
    ].join('\n');

    const formatted = formatText(typesFile);

    fs.writeFileSync(
      path.resolve(__dirname, `../src/types/${plugin.shortName}/index.ts`),
      formatted,
      'utf8'
    );

    console.info('Wrote types for', plugin.name, '\n');
  }

  console.info('Done!');
}
