branches:
  - main

plugins:
  - ['@semantic-release/commit-analyzer', { preset: 'conventionalcommits' }]
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/changelog'
  - ['@semantic-release/npm', { npmPublish: false }]
  - [
      '@semantic-release/exec',
      { publishCmd: 'yarn npm publish --access public' },
    ]
  - [
      '@semantic-release/git',
      {
        assets: [CHANGELOG.md, package.json, yarn.lock],
        message: "chore(release): ${nextRelease.gitTag} \n\n${nextRelease.notes}",
      },
    ]
  - '@semantic-release/github'
