import { createDocComment } from './docComment.js';

export const AUTO_GENERATED_NOTE = createDocComment(
  'THIS FILE IS AUTO-GENERATED.',
  'DO NOT MODIFY IT MANUALLY',
  'RUN `pnpm generate:types` TO REGENERATE IT.'
);

export function prependAutoGeneratedNote(code: string): string {
  return `${AUTO_GENERATED_NOTE}\n\n${code}`;
}
