export const AUTO_GENERATED_NOTE = `
/**
 * THIS FILE IS AUTO-GENERATED.
 * RUN \`pnpm generate:types\` TO REGENERATE IT.
 */
`;

export function prefixAutoGeneratedNote(code: string): string {
  return [AUTO_GENERATED_NOTE, code].join('\n');
}
