import type { TSESLint } from '@typescript-eslint/utils';
import fs from 'fs';
import path from 'path';
import { format } from 'prettier';
import url from 'url';

import prettierConfig from '../.prettierrc.json' assert { type: 'json' };
import packageJson from '../package.json' assert { type: 'json' };
import { AUTO_GENERATED_NOTE } from './autoGeneratedNote.js';
import {
  convertRuleOptionsToTypescriptTypes,
  type Plugin,
} from './convertRuleOptionsToTypes.js';
import { toPascalCase } from './toPascalCase.js';

const __dirname = url.fileURLToPath(new URL('.', import.meta.url));

type PendingPlugin = {
  name: string;
  rules: TSESLint.Linter.Plugin['rules'] | null;
  shortName: string;
};

async function getESLintCoreRules(): Promise<PendingPlugin> {
  const { builtinRules: eslintRules } = await import(
    'eslint/use-at-your-own-risk'
  );
  const plugin: Plugin = {
    name: 'eslint',
    rules: {},
    shortName: 'eslint',
  };
  eslintRules.forEach((rule, ruleId) => {
    // we need to explicitly iterate over each rule to ensure it gets loaded
    plugin.rules[ruleId] = rule;
  });

  return plugin;
}

/**
 * @returns list of all the eslint plugins installed
 */
function getAllPlugins(): Array<Promise<PendingPlugin>> {
  const deps = {
    ...packageJson.peerDependencies,
    ...packageJson.dependencies,
  };
  // const deps = { 'eslint-plugin-import': '^2.26.0' };
  return Object.keys(deps)
    .filter(
      (d) =>
        d.startsWith('eslint-plugin-') ||
        d.endsWith('/eslint-plugin') ||
        d.includes('/eslint-plugin-')
    )
    .map<Promise<PendingPlugin>>(async (d) => {
      // eslint-disable-next-line @typescript-eslint/consistent-type-assertions -- dynamic import is untyped
      const plugin = (await import(d)) as TSESLint.Linter.Plugin;
      return {
        rules: plugin.rules ? { ...plugin.rules } : null,
        name: d,
        shortName: d
          .replace(/^eslint-plugin-/u, '')
          .replace(/\/eslint-plugin$/u, '')
          .replace(/\/eslint-plugin-/u, '/'),
      };
    })
    .concat(getESLintCoreRules());
}

async function main(): Promise<void> {
  const plugins = getAllPlugins();

  for await (const plugin of plugins) {
    if (!plugin.rules) {
      continue;
    }

    const rules: Plugin['rules'] = {};
    for (const [ruleName, rule] of Object.entries(plugin.rules)) {
      if (typeof rule === 'function') {
        // normalise functional rules
        rules[ruleName] = {
          defaultOptions: [],
          meta: {
            messages: {},
            schema: {},
            type: 'suggestion',
          },
          create: rule,
        };
      } else if (rule.meta.deprecated === true) {
        // filter deprecated rules
        continue;
      } else {
        rules[ruleName] = rule;
      }
    }

    await convertRuleOptionsToTypescriptTypes({
      ...plugin,
      rules,
    });

    const ruleNames = Object.keys(rules).map((rule) => ({
      name: rule,
      safeName: toPascalCase(rule.replace(`${plugin.shortName}/`, '')),
    }));
    const interfaceName = toPascalCase(plugin.shortName);

    const typesFile = [
      AUTO_GENERATED_NOTE,
      '',
      ...ruleNames.map(
        (rule) =>
          `import type { ${rule.safeName} } from '../${plugin.shortName}/${rule.name}.js'`
      ),
      '',
      `interface ${interfaceName} {`,
      ...ruleNames.map(
        (rule) =>
          `'${plugin.shortName === 'eslint' ? '' : `${plugin.shortName}/`}${
            rule.name
          }': ${rule.safeName};`
      ),
      '}',
      '',
      'export type {',
      `    ${interfaceName}`,
      '};',
      '',
    ].join('\n');

    const formatted = format(typesFile, {
      parser: 'typescript',
      ...prettierConfig,
    });

    fs.writeFileSync(
      path.resolve(__dirname, `../src/types/${plugin.shortName}/index.ts`),
      formatted,
      'utf8'
    );

    console.info('Wrote types for', plugin.name, '\n');
  }

  console.info('Done!');
}

void main();

export type { Plugin };
