/**
 * THIS FILE IS AUTO-GENERATED.
 * RUN `pnpm generate:types` TO REGENERATE IT.
 */

import type { BooleanPropNaming } from '../react/boolean-prop-naming.js';
import type { ButtonHasType } from '../react/button-has-type.js';
import type { DefaultPropsMatchPropTypes } from '../react/default-props-match-prop-types.js';
import type { DestructuringAssignment } from '../react/destructuring-assignment.js';
import type { DisplayName } from '../react/display-name.js';
import type { ForbidComponentProps } from '../react/forbid-component-props.js';
import type { ForbidDomProps } from '../react/forbid-dom-props.js';
import type { ForbidElements } from '../react/forbid-elements.js';
import type { ForbidForeignPropTypes } from '../react/forbid-foreign-prop-types.js';
import type { ForbidPropTypes } from '../react/forbid-prop-types.js';
import type { FunctionComponentDefinition } from '../react/function-component-definition.js';
import type { HookUseState } from '../react/hook-use-state.js';
import type { IframeMissingSandbox } from '../react/iframe-missing-sandbox.js';
import type { JsxBooleanValue } from '../react/jsx-boolean-value.js';
import type { JsxChildElementSpacing } from '../react/jsx-child-element-spacing.js';
import type { JsxClosingBracketLocation } from '../react/jsx-closing-bracket-location.js';
import type { JsxClosingTagLocation } from '../react/jsx-closing-tag-location.js';
import type { JsxCurlySpacing } from '../react/jsx-curly-spacing.js';
import type { JsxCurlyNewline } from '../react/jsx-curly-newline.js';
import type { JsxEqualsSpacing } from '../react/jsx-equals-spacing.js';
import type { JsxFilenameExtension } from '../react/jsx-filename-extension.js';
import type { JsxFirstPropNewLine } from '../react/jsx-first-prop-new-line.js';
import type { JsxHandlerNames } from '../react/jsx-handler-names.js';
import type { JsxIndent } from '../react/jsx-indent.js';
import type { JsxIndentProps } from '../react/jsx-indent-props.js';
import type { JsxKey } from '../react/jsx-key.js';
import type { JsxMaxDepth } from '../react/jsx-max-depth.js';
import type { JsxMaxPropsPerLine } from '../react/jsx-max-props-per-line.js';
import type { JsxNewline } from '../react/jsx-newline.js';
import type { JsxNoBind } from '../react/jsx-no-bind.js';
import type { JsxNoCommentTextnodes } from '../react/jsx-no-comment-textnodes.js';
import type { JsxNoConstructedContextValues } from '../react/jsx-no-constructed-context-values.js';
import type { JsxNoDuplicateProps } from '../react/jsx-no-duplicate-props.js';
import type { JsxNoLeakedRender } from '../react/jsx-no-leaked-render.js';
import type { JsxNoLiterals } from '../react/jsx-no-literals.js';
import type { JsxNoScriptUrl } from '../react/jsx-no-script-url.js';
import type { JsxNoTargetBlank } from '../react/jsx-no-target-blank.js';
import type { JsxNoUselessFragment } from '../react/jsx-no-useless-fragment.js';
import type { JsxOneExpressionPerLine } from '../react/jsx-one-expression-per-line.js';
import type { JsxNoUndef } from '../react/jsx-no-undef.js';
import type { JsxCurlyBracePresence } from '../react/jsx-curly-brace-presence.js';
import type { JsxPascalCase } from '../react/jsx-pascal-case.js';
import type { JsxFragments } from '../react/jsx-fragments.js';
import type { JsxPropsNoMultiSpaces } from '../react/jsx-props-no-multi-spaces.js';
import type { JsxPropsNoSpreading } from '../react/jsx-props-no-spreading.js';
import type { JsxSortDefaultProps } from '../react/jsx-sort-default-props.js';
import type { JsxSortProps } from '../react/jsx-sort-props.js';
import type { JsxTagSpacing } from '../react/jsx-tag-spacing.js';
import type { JsxUsesReact } from '../react/jsx-uses-react.js';
import type { JsxUsesVars } from '../react/jsx-uses-vars.js';
import type { JsxWrapMultilines } from '../react/jsx-wrap-multilines.js';
import type { NoInvalidHtmlAttribute } from '../react/no-invalid-html-attribute.js';
import type { NoAccessStateInSetstate } from '../react/no-access-state-in-setstate.js';
import type { NoAdjacentInlineElements } from '../react/no-adjacent-inline-elements.js';
import type { NoArrayIndexKey } from '../react/no-array-index-key.js';
import type { NoArrowFunctionLifecycle } from '../react/no-arrow-function-lifecycle.js';
import type { NoChildrenProp } from '../react/no-children-prop.js';
import type { NoDanger } from '../react/no-danger.js';
import type { NoDangerWithChildren } from '../react/no-danger-with-children.js';
import type { NoDeprecated } from '../react/no-deprecated.js';
import type { NoDidMountSetState } from '../react/no-did-mount-set-state.js';
import type { NoDidUpdateSetState } from '../react/no-did-update-set-state.js';
import type { NoDirectMutationState } from '../react/no-direct-mutation-state.js';
import type { NoFindDomNode } from '../react/no-find-dom-node.js';
import type { NoIsMounted } from '../react/no-is-mounted.js';
import type { NoMultiComp } from '../react/no-multi-comp.js';
import type { NoNamespace } from '../react/no-namespace.js';
import type { NoSetState } from '../react/no-set-state.js';
import type { NoStringRefs } from '../react/no-string-refs.js';
import type { NoRedundantShouldComponentUpdate } from '../react/no-redundant-should-component-update.js';
import type { NoRenderReturnValue } from '../react/no-render-return-value.js';
import type { NoThisInSfc } from '../react/no-this-in-sfc.js';
import type { NoTypos } from '../react/no-typos.js';
import type { NoUnescapedEntities } from '../react/no-unescaped-entities.js';
import type { NoUnknownProperty } from '../react/no-unknown-property.js';
import type { NoUnsafe } from '../react/no-unsafe.js';
import type { NoUnstableNestedComponents } from '../react/no-unstable-nested-components.js';
import type { NoUnusedClassComponentMethods } from '../react/no-unused-class-component-methods.js';
import type { NoUnusedPropTypes } from '../react/no-unused-prop-types.js';
import type { NoUnusedState } from '../react/no-unused-state.js';
import type { NoWillUpdateSetState } from '../react/no-will-update-set-state.js';
import type { PreferEs6Class } from '../react/prefer-es6-class.js';
import type { PreferExactProps } from '../react/prefer-exact-props.js';
import type { PreferReadOnlyProps } from '../react/prefer-read-only-props.js';
import type { PreferStatelessFunction } from '../react/prefer-stateless-function.js';
import type { PropTypes } from '../react/prop-types.js';
import type { ReactInJsxScope } from '../react/react-in-jsx-scope.js';
import type { RequireDefaultProps } from '../react/require-default-props.js';
import type { RequireOptimization } from '../react/require-optimization.js';
import type { RequireRenderReturn } from '../react/require-render-return.js';
import type { SelfClosingComp } from '../react/self-closing-comp.js';
import type { SortComp } from '../react/sort-comp.js';
import type { SortPropTypes } from '../react/sort-prop-types.js';
import type { StateInConstructor } from '../react/state-in-constructor.js';
import type { StaticPropertyPlacement } from '../react/static-property-placement.js';
import type { StylePropObject } from '../react/style-prop-object.js';
import type { VoidDomElementsNoChildren } from '../react/void-dom-elements-no-children.js';

interface React {
  'react/boolean-prop-naming': BooleanPropNaming;
  'react/button-has-type': ButtonHasType;
  'react/default-props-match-prop-types': DefaultPropsMatchPropTypes;
  'react/destructuring-assignment': DestructuringAssignment;
  'react/display-name': DisplayName;
  'react/forbid-component-props': ForbidComponentProps;
  'react/forbid-dom-props': ForbidDomProps;
  'react/forbid-elements': ForbidElements;
  'react/forbid-foreign-prop-types': ForbidForeignPropTypes;
  'react/forbid-prop-types': ForbidPropTypes;
  'react/function-component-definition': FunctionComponentDefinition;
  'react/hook-use-state': HookUseState;
  'react/iframe-missing-sandbox': IframeMissingSandbox;
  'react/jsx-boolean-value': JsxBooleanValue;
  'react/jsx-child-element-spacing': JsxChildElementSpacing;
  'react/jsx-closing-bracket-location': JsxClosingBracketLocation;
  'react/jsx-closing-tag-location': JsxClosingTagLocation;
  'react/jsx-curly-spacing': JsxCurlySpacing;
  'react/jsx-curly-newline': JsxCurlyNewline;
  'react/jsx-equals-spacing': JsxEqualsSpacing;
  'react/jsx-filename-extension': JsxFilenameExtension;
  'react/jsx-first-prop-new-line': JsxFirstPropNewLine;
  'react/jsx-handler-names': JsxHandlerNames;
  'react/jsx-indent': JsxIndent;
  'react/jsx-indent-props': JsxIndentProps;
  'react/jsx-key': JsxKey;
  'react/jsx-max-depth': JsxMaxDepth;
  'react/jsx-max-props-per-line': JsxMaxPropsPerLine;
  'react/jsx-newline': JsxNewline;
  'react/jsx-no-bind': JsxNoBind;
  'react/jsx-no-comment-textnodes': JsxNoCommentTextnodes;
  'react/jsx-no-constructed-context-values': JsxNoConstructedContextValues;
  'react/jsx-no-duplicate-props': JsxNoDuplicateProps;
  'react/jsx-no-leaked-render': JsxNoLeakedRender;
  'react/jsx-no-literals': JsxNoLiterals;
  'react/jsx-no-script-url': JsxNoScriptUrl;
  'react/jsx-no-target-blank': JsxNoTargetBlank;
  'react/jsx-no-useless-fragment': JsxNoUselessFragment;
  'react/jsx-one-expression-per-line': JsxOneExpressionPerLine;
  'react/jsx-no-undef': JsxNoUndef;
  'react/jsx-curly-brace-presence': JsxCurlyBracePresence;
  'react/jsx-pascal-case': JsxPascalCase;
  'react/jsx-fragments': JsxFragments;
  'react/jsx-props-no-multi-spaces': JsxPropsNoMultiSpaces;
  'react/jsx-props-no-spreading': JsxPropsNoSpreading;
  'react/jsx-sort-default-props': JsxSortDefaultProps;
  'react/jsx-sort-props': JsxSortProps;
  'react/jsx-tag-spacing': JsxTagSpacing;
  'react/jsx-uses-react': JsxUsesReact;
  'react/jsx-uses-vars': JsxUsesVars;
  'react/jsx-wrap-multilines': JsxWrapMultilines;
  'react/no-invalid-html-attribute': NoInvalidHtmlAttribute;
  'react/no-access-state-in-setstate': NoAccessStateInSetstate;
  'react/no-adjacent-inline-elements': NoAdjacentInlineElements;
  'react/no-array-index-key': NoArrayIndexKey;
  'react/no-arrow-function-lifecycle': NoArrowFunctionLifecycle;
  'react/no-children-prop': NoChildrenProp;
  'react/no-danger': NoDanger;
  'react/no-danger-with-children': NoDangerWithChildren;
  'react/no-deprecated': NoDeprecated;
  'react/no-did-mount-set-state': NoDidMountSetState;
  'react/no-did-update-set-state': NoDidUpdateSetState;
  'react/no-direct-mutation-state': NoDirectMutationState;
  'react/no-find-dom-node': NoFindDomNode;
  'react/no-is-mounted': NoIsMounted;
  'react/no-multi-comp': NoMultiComp;
  'react/no-namespace': NoNamespace;
  'react/no-set-state': NoSetState;
  'react/no-string-refs': NoStringRefs;
  'react/no-redundant-should-component-update': NoRedundantShouldComponentUpdate;
  'react/no-render-return-value': NoRenderReturnValue;
  'react/no-this-in-sfc': NoThisInSfc;
  'react/no-typos': NoTypos;
  'react/no-unescaped-entities': NoUnescapedEntities;
  'react/no-unknown-property': NoUnknownProperty;
  'react/no-unsafe': NoUnsafe;
  'react/no-unstable-nested-components': NoUnstableNestedComponents;
  'react/no-unused-class-component-methods': NoUnusedClassComponentMethods;
  'react/no-unused-prop-types': NoUnusedPropTypes;
  'react/no-unused-state': NoUnusedState;
  'react/no-will-update-set-state': NoWillUpdateSetState;
  'react/prefer-es6-class': PreferEs6Class;
  'react/prefer-exact-props': PreferExactProps;
  'react/prefer-read-only-props': PreferReadOnlyProps;
  'react/prefer-stateless-function': PreferStatelessFunction;
  'react/prop-types': PropTypes;
  'react/react-in-jsx-scope': ReactInJsxScope;
  'react/require-default-props': RequireDefaultProps;
  'react/require-optimization': RequireOptimization;
  'react/require-render-return': RequireRenderReturn;
  'react/self-closing-comp': SelfClosingComp;
  'react/sort-comp': SortComp;
  'react/sort-prop-types': SortPropTypes;
  'react/state-in-constructor': StateInConstructor;
  'react/static-property-placement': StaticPropertyPlacement;
  'react/style-prop-object': StylePropObject;
  'react/void-dom-elements-no-children': VoidDomElementsNoChildren;
}

export type { React };
