name: Continuous Integration
on:
  push:
    branches:
      - '+([0-9])?(.{+([0-9]),x}).x'
      - main
      - next
      - next-major
      - beta
      - alpha
  pull_request: {}
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install Deps
        run: yarn install

      - name: Run Validate Script
        run: yarn validate
  release:
    needs: main
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'zmrl010/eslint-config' &&
      github.event_name == 'push' }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install Deps
        run: yarn install --immutable

      - name: Install Semantic Release
        run: |
          yarn add 
          semantic-release@19 
          @semantic-release/changelog@6.0.1 
          @semantic-release/exec@6.0.3 
          @semantic-release/git@10.0.1

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn semantic-release
