name: Continuous Integration
on:
  push:
    branches:
      - main
  pull_request: {}
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install Deps
        run: yarn install

      - name: Run Validate Script
        run: yarn validate
  release:
    needs: validate
    runs-on: ubuntu-latest
    if: github.repository == 'zmrl010/eslint-config'
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install Deps
        run: yarn install --immutable

      - name: Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: >
          yarn dlx
          -p semantic-release@19
          -p @semantic-release/changelog@6
          -p @semantic-release/exec@6
          -p @semantic-release/git@10
          -p conventional-changelog-conventionalcommits@5
          semantic-release
