name: Continuous Integration
on:
  push:
    branches:
      - main
  pull_request: {}
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install Deps
        run: pnpm install

      - name: Run Validate Script
        run: pnpm validate
  release:
    needs: validate
    runs-on: ubuntu-latest
    if: github.repository == 'zmrl010/eslint-config'
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install Deps
        run: pnpm install

      - name: Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: >
          pnpm dlx
          --project semantic-release@19
          --project @semantic-release/changelog@6
          --project @semantic-release/exec@6
          --project @semantic-release/git@10
          --project conventional-changelog-conventionalcommits@5
          semantic-release
